{{- if .Values.certManager.createClusterIssuer }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuerName }}
spec:
  acme:
    server: {{ if .Values.certManager.staging }}
      https://acme-staging-v02.api.letsencrypt.org/directory
    {{- else }}
      https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.certManager.email }}
    privateKeySecretRef:
      name: {{ .Values.certManager.clusterIssuerName }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className }}
{{- end }}
