# The URL the site will be built for
base_url = "https://an.kessler.xyz"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
theme = "radion"
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true


[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
comments = false

[markdown.math]
# Enable math rendering - options: "none", "katex", "typst" 
engine = "typst" # or "katex"

# Optional: Enable SVGO optimization for generated math SVGs
svgo = true # true, false, or "config_path"


css = "static/math.css"
