[package]
name = "tryptamine"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
axum = "0.7.7"
tokio =  { version = "1.4.0", features = ["full"] }

[[bin]]
name = "tryptamine"
path = "main.rs"
