[package]
name = "tryptamine"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
tokio =  { version = "1.4.0", features = ["rt", "rt-multi-thread"] }

[[bin]]
name = "tryptamine"
path = "main.rs"
