# local development docker compose
services:
  frontend:
    build:
      context: ./frontend-nextjs
      dockerfile: ./Dockerfile-dev
    # env_file:
    #   - config/global.env
    volumes:
      # - ./config/frontend.env.local:/app/.env.local
      # - ./config/global.env:/app/.env
      - ./frontend-nextjs/:/app/
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.namespace=tryptamine"

    ports:
      - 3001:3000

    expose:
      - 3000
    command:
      - "npm"
      - "run"
      - "dev"

  backend-rust:
    build:
      context: ./backend-rust/
      dockerfile: ./Dockerfile
    # env_file:
    #   - config/global.env

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/api`)"
      - "traefik.namespace=tryptamine"

    expose:
      - 3000
    command:
      - "./tryptamine"

  reverse-proxy:
    image: traefik:v3.1.2
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.constraints=Label(`traefik.namespace`,`tryptamine`)"
    expose:
      - 80
      - 443
    ports:
      - "81:80"
      - "${PROXY_UI_PORT:-8083}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
