# local development docker compose
services:
  reverse-proxy:
    image: traefik:v3.1.2
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - " -- traefik.http.routers.blog.tls.domains[0].main=example.com"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=nvenner@protonmail.ch"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--providers.docker.constraints=Label(`traefik.namespace`,`tryptamine`)"
    expose:
      - 80
      - 443
    ports:
      - 3443:443
      - "${PROXY_UI_PORT:-8084}:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${VOLUMES_DIRECTORY:-./volumes}/letsencrypt:/letsencrypt"
  frpc:
    image: snowdreamtech/frpc:alpine
    restart: always
    network_mode: "host"
    volumes:
      - ./frpc.toml:/etc/frp/frpc.toml

  frontend-nextjs:
    build:
      context: ./frontend-nextjs
      dockerfile: ./Dockerfile-dev
    # env_file:
    #   - config/global.env
    volumes:
      # - ./config/frontend.env.local:/app.env.local
      - ./config/global.env:/app/.env
    labels:
      - "traefik.enable=true"
      - "traefik.namespace=kessler"
      - "traefik.http.routers.frontend.rule=Host(`an.kessler.xyz`) && PathPrefix(`/`)"
      # - "traefik.http.routers.frontend.middlewares=state-redirect@file"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.routers.whoami.rule=Host(`n.kessler.xyz`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=myresolver"
    expose:
      - 3000
    command:
      # - "sleep"
      # - "9999999999d"
      - "npm"
      - "run"
      - "start"
