# frpc.toml
serverAddr = "frps-testing.tail4a273.ts.net"
serverPort = 7000

# [[proxies]]
# name = "webserver-insecure"
# type = "http"
# localPort = 80
# customDomains = ["frpmedia.kessler.xyz"]

[[proxies]]
name = "actionable-neighborhoods"
type = "https"
localPort = 4443
# localIP = "reverse-proxy"
customDomains = ["an.kessler.xyz"]

