# Default values for blog chart
replicaCount: 2

image:
  repository: "fractalhuman1/tryptamine-blog"
  tag: "7133e99ad3562666a7ac0a059aa52890f884add86ba8e60c064ea04ada3ba47c"
  pullPolicy: "IfNotPresent"

service:
  type: "ClusterIP"
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: "n.kessler.xyz"
      paths:
        - "/"
  tls:
    - secretName: "blog-tls"
      hosts:
        - "n.kessler.xyz"

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

nodeSelector: {}
tolerations: []
affinity: {}

certManager:
  email: "n@mycor.io"
  clusterIssuerName: "letsencrypt-prod"
