[package]
name = "mathematics-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.32", features = ["derive"] }
image = "0.25.5"
num-bigint = "0.4.6"
num-complex = "0.4.6"
palette = "0.7.6"
rand = "0.9.0"
rayon = "1.10.0"
