apiVersion: apps/v1
kind: Deployment
metadata:
  name: actionable-neighborhoods
  labels:
    app: actionable-neighborhoods
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: actionable-neighborhoods
  template:
    metadata:
      labels:
        app: actionable-neighborhoods
    spec:
      containers:
        - name: actionable-neighborhoods
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
