# ClusterIssuer for Let\u2019s Encrypt using cert-manager
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certManager.clusterIssuerName }}
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: actionable-neighborhoods-acme-key
    solvers:
      - http01:
          ingress:
            class: nginx
