apiVersion: v1
kind: Service
metadata:
  name: actionable-neighborhoods
  labels:
    app: actionable-neighborhoods
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: actionable-neighborhoods
