[package]
name = "tryptamine-tui"
version = "0.1.0"
description = "fractal generator tui"
authors = ["Nicole Venner <nvenner@protonmail.ch>"]
license = "MIT"
edition = "2024"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
color-eyre = "0.6.3"
palette = "0.7.6"
